version: '2'
services:
  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
   hostname: "elasticsearch"
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=\"*\""
      - "http.cors.allow-headers=Authorization"
      - "xpack.security.enabled=false"
      - "http.cors.enabled: true"
      - "http.cors.allow-origin: *"
   ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
   mem_limit: 1g
   cap_add:
   - IPC_LOCK
   volumes:
   - /Users/paguirre/elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.0
    hostname: "kibana"
    links:
      - elasticsearch
    ports:
      - 5601:5601